### ISSUE TITLE
Crash Unable to open usr/autorun/treefarm.lua

### ISSUE THREAD

**Issue by absolument** [kepler155c/opus-apps#14]
Hello,
I setup opus (1.8 stable) successfully via pastebin command `pastebin run uzghlbnc`, and then download packages (i'm interested by treefarm.lua), but it seems some apps crah...

(modpack: Tekxit 3 ; MC 1.12.2 ; CC:Tweaked 1.83.1 ; not Plethora)

Here are some errors messages:
treefarm.lua:82: Unable to open usr/autorun/treefarm.lua
kernel.lua:95: util.lua:402: Unable to open usr/config/shellprompt
util.lua:402: Unable to open usr/config/Files

After inspection dirs usr/apps ; usr/config ; usr/autorun are empty.
It's the first time i try opus, may i missed something...

**Comment by absolument** [comment]
Maybe explanation...
![2019-07-26_20 29 08](https://user-images.githubusercontent.com/17803584/61973363-28988800-afe4-11e9-80c3-db235dcf1671.png)

**Comment by xAnavrins** [comment]
Can you try again with 1.8 Unstable, this is the currently maintained branch and the most up to date at this moment, which might fix some of your issues.
You also seem to be running out of space on that computer, which might also cause problems. 
On 1.8 Unstable, you will also find a Disk Usage utility inside of the System app.

**Comment by absolument** [comment]
Yes, it was out of space
Solution: I remove unused packages, then it works well.
