### ISSUE TITLE
Farmer app: Not using charcoal as fuel

### ISSUE THREAD

**Issue by cynagen** [kepler155c/opus-apps#16]
Milo set up, depositing charcoal into 27th slot of plain oak chest, farmer app ignores it as fuel, thus running out in the middle of the field.

**Comment by xAnavrins** [comment]
I can't reproduce this, I've been running mine on charcoal and it works fine, though I have charcoal on slot 1 of my chest, but that shouldn't matter...

**Comment by cynagen** [comment]
I would argue that is not fully reproducing the issue, maybe set Milo to export charcoal to 27th and see what happens?

**Comment by xAnavrins** [comment]
I'm having the same results using the 27th slot.

**Comment by cynagen** [comment]
Well then, rebuilding turtles next.

**Comment by cynagen** [comment]
Rebuild (full software update) fixed it
