### ISSUE TITLE
Furnace Array turtle doesn't get recognised by Milo

### ISSUE THREAD

**Issue by Renjestoo** [kepler155c/opus-apps#18]
When trying to create a Furnace Array for Milo, I came to the conclusion that the Turtle that is responsable for the furnaces doesn't get recognised by Milo.

When using the "Devices" app in Opus, the turtle gets recognised without any issues.

I connected the turtle with a enabled wired modem on the top and on the bottom, but it still doesn't get recognised.
These versions are used by me...

- Minecraft 1.12.2
- cc-tweaked-1.12.2-1.82.3
- plethora-1.12.2-1.2.2

If more information is needed, please let me know.

PS:
I installed the latest version of Opus and all of the latest apps on the main turtle.
I even tried the stable version of Opus, but this didn't solve anything

**Comment by xAnavrins** [comment]
Make sure to use [develop-1,8](/kepler155c/opus/tree/develop-1.8) as it's the most updated branch right now.
The only thing that comes to mind, if filtering for that turtle in the Setup screen doesn't yield anything, is that this specific turtle got tagged as "ignored".
Try editing the file at `/usr/config/storage` to see if it is there, if it is, simply remove or comment out the `category = "ignore"` line.

Hopefully this fixes your issue, if not, if you happen to play on a server, I'd like to take a look at the issue directly, if possible.

**Comment by Renjestoo** [comment]
I indeed use develop-1,8
I can't see any turtles tagged as "ignored" in that file.
I checked for the ID on the turtle and its the correct ID I am looking in.
I even tried to edit the storage file, but that doesn't even change anything at all....

I even tried to use another advanced Turtle and set that up as the main Milo server... but it still doesn't recognise ANY turtles as an inventory in the setup screen.
I can see EVERY other inventory like drawers and furnaces and barrels and chests and other modded inventories, except for turtles...

I find this very... VERY strange.... hmmm.

Maybe I will hop on to the server one of these days...
Thanx anyway.

**Comment by Renjestoo** [comment]
ok... I got a little bit further...

I edited the storage file so that the turtle is forced to be seen as a "Machine" (just copied over the lines for the normal furnace since the turtle is using basically the same settings as a furnace)

Now I see the turtle in the Setup... BUT

Yep.. there is a but..
this now visible turtle can't be assigned to a type..
The only 2 options I have in the Setup page of Milo are:
- Ignore
- Hidden

I can't choose for Storage or Generic Inventory or some of that stuff....

This is again... very weird...

**Comment by xAnavrins** [comment]
I'm really out of idea, I have an up to date setup which sees a turtle connected from the front or back, or side to side, with or without an Introspection module.
The only difference is that I'm playing on;
cc-tweaked-1.12.2-1.82.1
plethora-1.12.2-1.1.14
So something probably broke with your versions, I'll investigate further soon.

**Comment by xAnavrins** [comment]
`turtle_12` doesn't mean that this turtle has ID 12 when typing `id` on it, instead it means that it's the 12th turtle in your world to be connected by a wired modem with a rightclick. 
To start the swarm miner, just double click the blocks to make a list of blocks to mine and it should work.

**Comment by Renjestoo** [comment]
owkay... well... the only other turtle i have connected to my network is the Main turtle that is running the Milo program... so thats the only "other" one that can be seen.

for the Swarm Miner...
Okay... it still doesn't work 

Let me send you a few screenshots of the Swarm miner setup

[https://imgur.com/a/WsnIZvh](url)

in the swarm miner program I see the turtles, but in the bottom left it says "turtles: 0"
"Queue: 166" (wich I know are the blocks about to be mined)

Why does it keep telling that there are 0 turtles, but that he sees the 4 turtles who have to mine?

Do the turtles have to run a specific program? Or do they just have to be idle in the Opus main menu? Since I can't see any Swarm program in them.

**Comment by xAnavrins** [comment]
Screenshot link is broken, make sure that you're fairly close to your turtles when launching multiminer

**Comment by kepler155c** [comment]
Make sure the swarm turtles have the "turtle" package installed. Also, make sure you can telnet to them - this ensures that the trust is setup correctly. When I set this up, I get one turtle working properly then I use the DiskCopy program to get the rest of the swarm turtles setup (using the first turtle as the source for the copying).

**Comment by Renjestoo** [comment]
Yep the Swarm turtles work now :) I was never thinking about the Telnet connections :)

But then there is the problem with the Milo network not seeing the Furnace Array turtle...
Could you explain that to me?
