### ISSUE TITLE
Invalid package

### ISSUE THREAD

**Issue by EbenMK** [kepler155c/opus-apps#31]
When i do package install milo it says "package.lua:60: Invalid package"

**Comment by xAnavrins** [comment]
What version of CC or CC:Tweaked are you using, do you have the Plethora mod installed?
What Opus branch are you using, if Milo isn't found this means you are using master-1.7 or develop-1.7.
Milo is only available on the master-1.8 and develop-1.8 branches, and will only work on a recent version of CC:Tweaked and Plethora.

**Comment by EbenMK** [comment]
I'm using CCT 1.86.2, Plethora 1.2.3, and using master-1.8. Also on minecraft 1.12.2 if that matters.

**Comment by xAnavrins** [comment]
This all looks good, please use the develop-1.8 branch instead as it's the most up-to-date branch.
