### ISSUE TITLE
Nyan cat screensaver unexpectedly activating on monitors causes 30k peripheral calls per second

### ISSUE THREAD

**Issue by Kan18** [kepler155c/opus-apps#33]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/24967425/79702818-84432980-8275-11ea-88d4-1d75d6f12924.png">
While updating my Milo turtle on Switchcraft, I installed the screensavers package because I thought it would be cool. The "nyan cat" screensaver, when it was activated on a monitor, used over 30k peripheral calls per second. This reduces the server's performance and the nyan cat program should be optimized to use less peripheral calls. Also, there should be configuration for the screensavers package including the option to change if monitors can have screensavers on them. Related issue: the "screensavers" package has to be uninstalled multiple times in a row due to the urlfs'ed parts.

**Comment by kepler155c** [comment]
Removed the nyan cat screensaver - thanks for the info.
