### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by EbenMK** [kepler155c/opus-apps#34]
Is there any way to get Milo to save recipes to a disk instead of the HDD? I can't even access my settings because there's no space.

**Comment by kepler155c** [comment]
I created a new program called 'Partition' (System->Partition) that will allow you to move either the packages directory or the usr/config directory to a disk. Note that you can use a labeled computer in a disk drive for more space. You will need to run System->Update and Packages->Update All before running this new program.
