### ISSUE TITLE
pastebin run uzghlbnc, no longer works, and the case sensitive link is not available on your wiki.

### ISSUE THREAD

**Issue by DistantT** [kepler155c/opus-apps#42]
pastebin run uzghlbnc, no longer works, and the case sensitive link is not available on your wiki.
Up until very recently all the links you published in the wiki etc  were the full case sensitive version. They have all just changed to lower case which doesn't work.
For anyone else reading the case sensitive version is pastebin run UzGHLbNC

**Comment by xAnavrins** [comment]
This is already fixed in the readme.
