### ISSUE TITLE
milo won't pull from slot 3 of furnace

### ISSUE THREAD

**Issue by thm51b8f2d68cs** [kepler155c/opus-apps#44]
I have tried resetting it multiple times and made new furnaces and reconnected them and my milo will not retrieve the items from slot 3
![2020-07-28_12 25 29](https://user-images.githubusercontent.com/68766033/88711733-76e7d780-d0cd-11ea-944e-4be31b2c83eb.png)
![2020-07-28_12 25 34](https://user-images.githubusercontent.com/68766033/88711746-7e0ee580-d0cd-11ea-9512-abc7086f3005.png)

**Comment by xAnavrins** [comment]
Are they set up as generic inventories, _and_ set up to import from slot 3 ?

**Comment by thm51b8f2d68cs** [comment]
Yes I have them set up as generic inventories.  I was only able to get them to work by whitelisting each item one by one.  In the demonstration video it shows just to select slot 3 and add no filters and that should remove items from slot 3.
________________________________
