### ISSUE TITLE
Milo does not pick up any turtles making furnace arrays unusable

### ISSUE THREAD

**Issue by z256z** [kepler155c/opus-apps#48]
So as the title basically said.
The turtle running the furnace array program works and even picks up all the furnaces as expected, it is milo that does not seems to pick up the turtle (or any at all)

I took a look at the other submitted issue to get any ideas and got no results from it

latest version of opus and milo
turtle running opus is advanced and tried both advanced and regular for the furnace setup
all mods up-to-date and running 1.12.2

tried multiple configurations and rebooted both turtles multiple times after any change. Already checked the config file and reset it to be sure
the server I was playing on restarted to confirm it was not a server issue

**Comment by xAnavrins** [comment]
Try placing the wired modems on sides other than left and right, since those sides are usually used for the turtle left and right equipment.

**Comment by z256z** [comment]
I have tried all sides of both milo and the furnace setup and it does not seem to pick it up

**Comment by xAnavrins** [comment]
I can't reproduce...
Which branch are you on, develop-1.8, master-1.8, develop, master?
Look in the `/usr/config/storage` file and check if that turtle is in there with an `mtype` of "hidden", if it is, change it to "ignore", make sure it is the ID of the array turtle and not the Milo turtle.

**Comment by z256z** [comment]
So it appears in the config however when I change it from "hidden" to "ignore" it does nothing. I would also like to let you know that I do have a drive connected if that has to to with any of this (as a backup drive) - all of which have the turtle in the storage file and set to "ignore" but does not show in milo. I have discord Koga#7985 also in the computercraft and switchcraft discord if you need me ping me
