### ISSUE TITLE
weird turtle movement bug when connecting to wired modem

### ISSUE THREAD

**Issue by Kan18** [kepler155c/opus-apps#52]
If the turtle moves under an activated wired modem (see image), the turtle movement call will yield until terminated
![image](https://user-images.githubusercontent.com/24967425/130866251-a3e9c0e7-1fbf-4e80-ac9f-b34e4d1206e9.png)

This doesn't happen when booting into CraftOS (also: sorry if this is the wrong repo for the bug, but all the turtle movement stuff is in the turtle package)
video: https://user-images.githubusercontent.com/24967425/130865756-1006864c-26c9-48b4-ab85-b34d81c2cf8d.mov
workaround: put the wired modem in a place where the turtle won't accidentally touch it

**Comment by xAnavrins** [comment]
I can't reproduce, what programs were running while this happened, which script and line did the yield error occur on?

**Comment by Kan18** [comment]
I couldn't reproduce this either (on the same wired network) so I will close this for now. Here is the original video which GitHub seems to have deleted (it cuts off, but there was no error - it just waited)  https://streamable.com/nwya34  (edit: wow, streamable recently emailed me to inform me that they're deleting the video too, I doubt anybody will care at all but if anybody wants to see the original video (why would you want to? it's not like this is still happening (edit2: wow, this was proven wrong very quickly)) here's the new link https://cdn.discordapp.com/attachments/477911902152949771/1012556290091917333/Screen_Recording_2021-08-25_at_5.12.22_PM.mov )

**Comment by Kan18** [comment]
I managed to reproduce this in my base again. The turtle didn't even have the `turtle` package installed. Notably `#peripheral.getNames()` on the turtle when it's under the wired modem shows 275. The bug doesn't happen when the wired modem that the turtle is under is disconnected from my base network. I think all the peripheral events might be overflowing and preventing the CC code from receiving the turtle movement event thing and exiting turtle.forward(). I am not exactly sure how opus would be causing it (the bug still doesn't happen when booting into craftos) but I think it is either the `device` system generating a bunch of events or something weird happening with the kernel hooks.

https://user-images.githubusercontent.com/24967425/186809957-22ebcd40-8b90-40d5-b2ab-e546cc941e47.mp4

**Comment by Kan18** [comment]
I got this to reproduce without Opus OS under a specific set of circumstances (cc-tweaked/cc-tweaked#1155) so will be closing for now

**Comment by xAnavrins** [comment]
Ah interesting, you might need to segment your networks then, one that transfers items from the turtles into a chest, and your Milo that has this chest as an input chest.
